// Generated by hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge on 08/20/2014 15:58:07-0300.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package com.googlecode.ouvidoria.negocio.localidade;

import com.googlecode.ouvidoria.negocio.localidade.vo.MunicipioVO;

/**
 * @see Municipio
 */
public class MunicipioDaoImpl
    extends MunicipioDaoBase
{
    /**
     * {@inheritDoc}
     */
    @Override
    public void toMunicipioVO(
        Municipio source,
        MunicipioVO target)
    {
        // TODO verify behavior of toMunicipioVO
        super.toMunicipioVO(source, target);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MunicipioVO toMunicipioVO(final Municipio entity)
    {
        // TODO verify behavior of toMunicipioVO
        return super.toMunicipioVO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private Municipio loadMunicipioFromMunicipioVO(MunicipioVO municipioVO)
    {
        // TODO implement loadMunicipioFromMunicipioVO
        throw new UnsupportedOperationException("com.googlecode.ouvidoria.negocio.localidade.loadMunicipioFromMunicipioVO(MunicipioVO) not yet implemented.");

        /* A typical implementation looks like this:
        if (municipioVO.getId() == null)
        {
            return  Municipio.Factory.newInstance();
        }
        else
        {
            return this.load(municipioVO.getId());
        }
        */
    }

    /**
     * {@inheritDoc}
     */
    public Municipio municipioVOToEntity(MunicipioVO municipioVO)
    {
        // TODO verify behavior of municipioVOToEntity
        Municipio entity = this.loadMunicipioFromMunicipioVO(municipioVO);
        this.municipioVOToEntity(municipioVO, entity, true);
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void municipioVOToEntity(
        MunicipioVO source,
        Municipio target,
        boolean copyIfNull)
    {
        // TODO verify behavior of municipioVOToEntity
        super.municipioVOToEntity(source, target, copyIfNull);
    }
}