// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package com.googlecode.ouvidoria.presentation.start;

/**
 * @see com.googlecode.ouvidoria.presentation.start.MainScreenCTL
 */
public class MainScreenCTLImpl
    extends MainScreenCTL
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -3605955620360314995L;

}