// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package com.googlecode.ouvidoria.presentation.complaint.answer;

import com.googlecode.ouvidoria.model.complaint.vo.AnswerVO;
import com.googlecode.ouvidoria.model.complaint.vo.ComplaintVO;

/**
 * @see com.googlecode.ouvidoria.presentation.complaint.answer.AnswerComplaintCTL
 */
public class AnswerComplaintCTLImpl extends AnswerComplaintCTL {
	/**
	 * The serial version UID of this class. Needed for serialization.
	 */
	private static final long serialVersionUID = 5808024099281688685L;

	/**
	 * @see com.googlecode.ouvidoria.presentation.complaint.answer.AnswerComplaintCTL#isParameterPresent()
	 */
	@Override
	public boolean isParameterPresent() {
		System.out
				.println("******************** getComplaintSessionObject().getComplaintId()="
						+ getComplaintSessionObject().getComplaintId());

		return getComplaintSessionObject().getComplaintId() != null
				&& getComplaintSessionObject().getComplaintId() > 0;
	}

	/**
	 * @see com.googlecode.ouvidoria.presentation.complaint.answer.AnswerComplaintCTL#populateScreen(java.lang.Long
	 *      complaintId, java.lang.String date, java.lang.String text)
	 */
	@Override
	public void populateScreen(PopulateScreenForm form) {
		ComplaintVO vo = getComplaintService().load(getComplaintSessionObject().getComplaintId());
		
		form.setComplaintId(vo.getId());
		form.setText(vo.getText());
		form.setDate(vo.getDate().toString());
	}

	/**
	 * @see com.googlecode.ouvidoria.presentation.complaint.answer.AnswerComplaintCTL#persistAnswer(java.lang.Long
	 *      complaintId, java.lang.String answer)
	 */
	@Override
	public void persistAnswer(PersistAnswerForm form) {
		AnswerVO vo = new AnswerVO();
		vo.setComplaintId(getComplaintSessionObject().getComplaintId());
		vo.setText(form.getAnswer());
		getComplaintService().answer(vo);
	}

}