// Generated by hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge on 08/20/2014 15:58:07-0300.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package com.googlecode.ouvidoria.negocio.localidade;

import com.googlecode.ouvidoria.negocio.localidade.vo.UnidadeFederacaoVO;

/**
 * @see UnidadeFederacao
 */
public class UnidadeFederacaoDaoImpl
    extends UnidadeFederacaoDaoBase
{
    /**
     * {@inheritDoc}
     */
    @Override
    public void toUnidadeFederacaoVO(
        UnidadeFederacao source,
        UnidadeFederacaoVO target)
    {
        // TODO verify behavior of toUnidadeFederacaoVO
        super.toUnidadeFederacaoVO(source, target);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UnidadeFederacaoVO toUnidadeFederacaoVO(final UnidadeFederacao entity)
    {
        // TODO verify behavior of toUnidadeFederacaoVO
        return super.toUnidadeFederacaoVO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private UnidadeFederacao loadUnidadeFederacaoFromUnidadeFederacaoVO(UnidadeFederacaoVO unidadeFederacaoVO)
    {
        // TODO implement loadUnidadeFederacaoFromUnidadeFederacaoVO
        throw new UnsupportedOperationException("com.googlecode.ouvidoria.negocio.localidade.loadUnidadeFederacaoFromUnidadeFederacaoVO(UnidadeFederacaoVO) not yet implemented.");

        /* A typical implementation looks like this:
        if (unidadeFederacaoVO.getId() == null)
        {
            return  UnidadeFederacao.Factory.newInstance();
        }
        else
        {
            return this.load(unidadeFederacaoVO.getId());
        }
        */
    }

    /**
     * {@inheritDoc}
     */
    public UnidadeFederacao unidadeFederacaoVOToEntity(UnidadeFederacaoVO unidadeFederacaoVO)
    {
        // TODO verify behavior of unidadeFederacaoVOToEntity
        UnidadeFederacao entity = this.loadUnidadeFederacaoFromUnidadeFederacaoVO(unidadeFederacaoVO);
        this.unidadeFederacaoVOToEntity(unidadeFederacaoVO, entity, true);
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void unidadeFederacaoVOToEntity(
        UnidadeFederacaoVO source,
        UnidadeFederacao target,
        boolean copyIfNull)
    {
        // TODO verify behavior of unidadeFederacaoVOToEntity
        super.unidadeFederacaoVOToEntity(source, target, copyIfNull);
    }
}