// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package com.googlecode.ouvidoria.presentation.complaint.internet.check;

/**
 * @see com.googlecode.ouvidoria.presentation.complaint.internet.check.AcompanhaDemandaCTL
 */
public class AcompanhaDemandaCTLImpl
    extends AcompanhaDemandaCTL
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 8039592399882634611L;

    /**
     * @see com.googlecode.ouvidoria.presentation.complaint.internet.check.AcompanhaDemandaCTL#populaTelaConsulta(java.lang.Long codigo, java.lang.String senha)
     */
    @Override
    public void populaTelaConsulta(PopulaTelaConsultaForm form)
    {
    }

    /**
     * @see com.googlecode.ouvidoria.presentation.complaint.internet.check.AcompanhaDemandaCTL#consultaDemanda(java.lang.Long codigo, java.lang.String senha)
     */
    @Override
    public void consultaDemanda(ConsultaDemandaForm form)
    {
    }

}