// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package com.googlecode.ouvidoria.presentation.complaint.check;

/**
 * @see com.googlecode.ouvidoria.presentation.complaint.check.CheckComplaintStatusCTL
 */
public class CheckComplaintStatusCTLImpl
    extends CheckComplaintStatusCTL
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 7047923472788647060L;

    /**
     * @see com.googlecode.ouvidoria.presentation.complaint.check.CheckComplaintStatusCTL#populateScreen(java.lang.Long code, java.lang.String password)
     */
    @Override
    public void populateScreen(PopulateScreenForm form)
    {
    }

    /**
     * @see com.googlecode.ouvidoria.presentation.complaint.check.CheckComplaintStatusCTL#checkComplaint(java.lang.Long code, java.lang.String password)
     */
    @Override
    public boolean checkComplaint(CheckComplaintForm form)
    {
        return false;
    }

    /**
     * @see com.googlecode.ouvidoria.presentation.complaint.check.CheckComplaintStatusCTL#initializeComplaintId(java.lang.Long code, java.lang.Long complaintId)
     */
    @Override
    public void initializeComplaintId(InitializeComplaintIdForm form)
    {
    }

}