// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package com.googlecode.ouvidoria.presentation.complaint.close;

/**
 * @see com.googlecode.ouvidoria.presentation.complaint.close.CloseComplaintCTL
 */
public class CloseComplaintCTLImpl
    extends CloseComplaintCTL
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -469100613836007410L;

    /**
     * @see com.googlecode.ouvidoria.presentation.complaint.close.CloseComplaintCTL#isParameterPresent()
     */
    @Override
    public boolean isParameterPresent()
    {
    	System.out.println("getComplaintSessionObject().getComplaintId()="+getComplaintSessionObject().getComplaintId());
    	/*
    	 * return getComplaintSessionObject().getComplaintId() != null
				&& getComplaintSessionObject().getComplaintId() > 0;
    	 */
        return false;
    }

    /**
     * @see com.googlecode.ouvidoria.presentation.complaint.close.CloseComplaintCTL#retrieveComplaint()
     */
    @Override
    public void retrieveComplaint()
    {
    }

    /**
     * @see com.googlecode.ouvidoria.presentation.complaint.close.CloseComplaintCTL#closeComplaint()
     */
    @Override
    public void closeComplaint()
    {
    }

}