// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package com.googlecode.ouvidoria.presentation.complaint.answer;

/**
 * @see com.googlecode.ouvidoria.presentation.complaint.answer.AnswerComplaintCTL
 */
public class AnswerComplaintCTLImpl
    extends AnswerComplaintCTL
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 5808024099281688685L;

    /**
     * @see com.googlecode.ouvidoria.presentation.complaint.answer.AnswerComplaintCTL#isParameterPresent()
     */
    @Override
    public boolean isParameterPresent()
    {
    	System.out.println("getComplaintSessionObject().getComplaintId()="+getComplaintSessionObject().getComplaintId());
    	/*
    	 * return getComplaintSessionObject().getComplaintId() != null
				&& getComplaintSessionObject().getComplaintId() > 0;
    	 */
        return false;
    }

    /**
     * @see com.googlecode.ouvidoria.presentation.complaint.answer.AnswerComplaintCTL#populateScreen(java.lang.Long complaintId, java.lang.String date, java.lang.String text)
     */
    @Override
    public void populateScreen(PopulateScreenForm form)
    {
    }

    /**
     * @see com.googlecode.ouvidoria.presentation.complaint.answer.AnswerComplaintCTL#persistAnswer(java.lang.Long complaintId, java.lang.String answer)
     */
    @Override
    public void persistAnswer(PersistAnswerForm form)
    {
    }

}