// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package com.googlecode.ouvidoria.presentation.complaint.internet.register;

import java.util.List;

import com.googlecode.ouvidoria.model.vo.SimpleVO;

/**
 * @see com.googlecode.ouvidoria.presentation.complaint.internet.register.RegisterComplaintCTL
 */
public class RegisterComplaintCTLImpl extends RegisterComplaintCTL {
	/**
	 * The serial version UID of this class. Needed for serialization.
	 */
	private static final long serialVersionUID = 7465615235771425976L;

	/**
	 * @see com.googlecode.ouvidoria.presentation.complaint.internet.register.RegisterComplaintCTL#populateScreen(java.lang.Long
	 *      demandantType, java.lang.String name, java.lang.Long sex,
	 *      java.lang.Long identification, java.lang.String document,
	 *      java.lang.String businessPhone, java.lang.String celularPhone,
	 *      java.lang.String email, java.lang.String address, java.lang.String
	 *      zipCode, java.lang.Long state, java.lang.Long city, java.lang.Long
	 *      type, java.lang.Long subject, java.lang.Long answer,
	 *      java.lang.String text)
	 */
	@Override
	public void populateScreen(PopulateScreenForm form) {
		List<SimpleVO> demandantTypes = getDemandantHelper().getDemandantTypes();
		form.setDemandantTypeBackingList(toSelectItemCollection(demandantTypes));
		
		List<SimpleVO> identificationTypes = getDemandantHelper().getIdentificationTypes();
		form.setIdentificationBackingList(toSelectItemCollection(identificationTypes));
		
		List<SimpleVO> sexTypes = getDemandantHelper().getSexTypes();
		form.setSexBackingList(toSelectItemCollection(sexTypes,false));
		
		List<SimpleVO> complaintTypes = getComplaintHelper().getComplaintTypes();
		form.setTypeBackingList(toSelectItemCollection(complaintTypes));
		
		List<SimpleVO> contacts = getComplaintHelper().getContacts();
		form.setAnswerBackingList(toSelectItemCollection(contacts,false));
		
		List<SimpleVO> subjects = getComplaintHelper().getSubjects();
		form.setSubjectBackingList(toSelectItemCollection(subjects));

		List<SimpleVO> statesList = getLocalityService().listStates();
		form.setStateBackingList(toSelectItemCollection(statesList));
	}

	/**
	 * @see com.googlecode.ouvidoria.presentation.complaint.internet.register.RegisterComplaintCTL#retrieveComplaint()
	 */
	@Override
	public void retrieveComplaint() {
	}

	/**
	 * @see com.googlecode.ouvidoria.presentation.complaint.internet.register.RegisterComplaintCTL#registerComplaint(java.lang.Long
	 *      demandantType, java.lang.String name, java.lang.Long sex,
	 *      java.lang.Long identification, java.lang.String document,
	 *      java.lang.String businessPhone, java.lang.String celularPhone,
	 *      java.lang.String email, java.lang.String address, java.lang.String
	 *      zipCode, java.lang.Long state, java.lang.Long city, java.lang.Long
	 *      type, java.lang.Long subject, java.lang.Long answer,
	 *      java.lang.String text)
	 */
	@Override
	public void registerComplaint(RegisterComplaintForm form) {
	}

	/**
	 * @see com.googlecode.ouvidoria.presentation.complaint.internet.register.RegisterComplaintCTL#validateComplaint(java.lang.Long
	 *      demandantType, java.lang.String name, java.lang.Long sex,
	 *      java.lang.Long identification, java.lang.String document,
	 *      java.lang.String businessPhone, java.lang.String celularPhone,
	 *      java.lang.String email, java.lang.String address, java.lang.String
	 *      zipCode, java.lang.Long state, java.lang.Long city, java.lang.Long
	 *      type, java.lang.Long subject, java.lang.Long answer,
	 *      java.lang.String text)
	 */
	@Override
	public boolean validateComplaint(ValidateComplaintForm form) {
		return false;
	}

}