// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package com.googlecode.ouvidoria.presentation.complaint.details;

import com.googlecode.ouvidoria.model.complaint.enums.Contact;
import com.googlecode.ouvidoria.model.complaint.vo.ComplaintVO;
import com.googlecode.ouvidoria.model.demandant.enums.Sex;

/**
 * @see com.googlecode.ouvidoria.presentation.complaint.details.ComplaintDetailsCTL
 */
public class ComplaintDetailsCTLImpl extends ComplaintDetailsCTL {
	/**
	 * The serial version UID of this class. Needed for serialization.
	 */
	private static final long serialVersionUID = 2744774673113236011L;

	@Override
	public void retrieveComplaint(RetrieveComplaintForm form) throws Throwable {
		Long complaintId = getComplaintSessionObject().getComplaintId();

		ComplaintVO complaint = getComplaintService().load(complaintId);
		
		form.setComplaintId(complaintId);
		form.setSubject(complaint.getSubject());
		form.setText(complaint.getText());
		form.setType(complaint.getType());
		form.setDate((complaint.getDate() == null)?"":complaint.getDate().toString());
		form.setAnswers(complaint.getAnswers());
		form.setStatus(complaint.getStatus().toString());
		
		if(complaint.getDemandant() != null){
			form.setAddress(complaint.getDemandant().getAddress());
			form.setBusinessPhone(complaint.getDemandant().getBusinessPhone());
			form.setCelularPhone(complaint.getDemandant().getCelularPhone());
			form.setCity(complaint.getDemandant().getCity());
			form.setDemandantType(complaint.getDemandant().getType());
			form.setDocument(complaint.getDemandant().getDocument());
			form.setEmail(complaint.getDemandant().getEmail());
			form.setIdentification(complaint.getDemandant().getIdentification());
			form.setName(complaint.getDemandant().getName());
			form.setState(complaint.getDemandant().getState());
			form.setZipCode(complaint.getDemandant().getZipCode());
			Sex sex = complaint.getDemandant().getSex();
			form.setSex((sex == null)?"":sex.toString());
		}
		
		Contact answerType = complaint.getAnswerType();
		form.setAnswerWay((answerType == null)?"":answerType.toString());
	}

	@Override
	public boolean isParameterPresent() throws Throwable {
		return getComplaintSessionObject().getComplaintId() != null
				&& getComplaintSessionObject().getComplaintId() > 0;
	}

}