// Generated by hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge on 12/08/2014 16:36:59-0200.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package com.googlecode.ouvidoria.model.user;

import com.googlecode.ouvidoria.model.user.vo.UserVO;

/**
 * @see User
 */
public class UserDaoImpl
    extends UserDaoBase
{
    /**
     * {@inheritDoc}
     */
    @Override
    public void toUserVO(
        User source,
        UserVO target)
    {
        // TODO verify behavior of toUserVO
        super.toUserVO(source, target);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserVO toUserVO(final User entity)
    {
        // TODO verify behavior of toUserVO
        return super.toUserVO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
        private User loadUserFromUserVO(UserVO vo)
    {
    	        User retorno = null;
		if(vo.getId() == null){
			retorno = User.Factory.newInstance();
		}else{
			retorno = load(vo.getId());
		}
		return retorno;	
		
        // TODO implement loadUserFromUserVO
        //throw new UnsupportedOperationException("com.googlecode.ouvidoria.model.user.loadUserFromUserVO(UserVO) not yet implemented.");

        /* A typical implementation looks like this:
        if (userVO.getId() == null)
        {
            return  User.Factory.newInstance();
        }
        else
        {
            return this.load(userVO.getId());
        }
        */
    }

    /**
     * {@inheritDoc}
     */
    public User userVOToEntity(UserVO userVO)
    {
        // TODO verify behavior of userVOToEntity
        User entity = this.loadUserFromUserVO(userVO);
        this.userVOToEntity(userVO, entity, true);
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void userVOToEntity(
        UserVO source,
        User target,
        boolean copyIfNull)
    {
        // TODO verify behavior of userVOToEntity
        super.userVOToEntity(source, target, copyIfNull);
    }
}