// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package com.googlecode.ouvidoria.presentation.complaint.search;

import java.util.ArrayList;
import java.util.SortedSet;
import java.util.TreeSet;

import com.googlecode.ouvidoria.model.complaint.vo.ResumedComplaintVO;

/**
 * @see com.googlecode.ouvidoria.presentation.complaint.search.ComplaintSearchCTL
 */
public class ComplaintSearchCTLImpl extends ComplaintSearchCTL {
	/**
	 * The serial version UID of this class. Needed for serialization.
	 */
	private static final long serialVersionUID = -5120859528350734637L;

	/**
	 * @see com.googlecode.ouvidoria.presentation.complaint.search.ComplaintSearchCTL#populateScreen(java.lang.Long
	 *      code, java.lang.String complaintStatus, java.lang.Long type,
	 *      java.lang.Long subject, java.lang.String text, java.lang.Long
	 *      demandantType, java.lang.String demandantName, java.lang.String
	 *      demandantDocument,
	 *      com.googlecode.ouvidoria.model.complaint.vo.ResumedComplaintVO
	 *      complaints)
	 */
	@Override
	public void populateScreen(PopulateScreenForm form) {
		System.out.println("populateScreen ............");
		
		
		SortedSet<ResumedComplaintVO> complaints = new TreeSet<ResumedComplaintVO>();
		complaints.add(new ResumedComplaintVO(1L,"13/12/2014","type-01","status-01","subject-01"));
		complaints.add(new ResumedComplaintVO(2L,"13/12/2014","type-02","status-02","subject-02"));
		complaints.add(new ResumedComplaintVO(3L,"13/12/2014","type-03","status-03","subject-03"));
		complaints.add(new ResumedComplaintVO(4L,"13/12/2014","type-04","status-04","subject-04"));
		form.setComplaints(complaints);
	}

}