// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package com.googlecode.ouvidoria.presentation.menu;

/**
 * @see com.googlecode.ouvidoria.presentation.menu.MenuCTL
 */
public class MenuCTLImpl
    extends MenuCTL
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -1953859217191234984L;

}