// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package com.googlecode.ouvidoria.presentation.inicio;

/**
 * @see com.googlecode.ouvidoria.presentation.inicio.MainScreenCTL
 */
public class MainScreenCTLImpl
    extends MainScreenCTL
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 2029981668726574915L;

}